
CREATE TABLE Climate (
	Region character varying(50) NOT NULL,
	Date DATE NOT NULL,
	PCP FLOAT NOT NULL,
	TAVG FLOAT NOT NULL,
	PDSI FLOAT NOT NULL,
	PHDI FLOAT NOT NULL,
	TMIN FLOAT NOT NULL,
	TMAX FLOAT NOT NULL,
	PRIMARY KEY (Region,Date)
);

